name: java11-maven
on: 
  workflow_call: 


jobs:
  java11-maven:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out 
        uses: actions/checkout@v3
      - name: set up java 11
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: 'temurin'          
      - name: build with maven
        run: |
            mvn -B package --file pom.xml
      - name: check pwd
        run: ls -a
      - name: check target folder 
        run: |
          cd target
          ls -a  
      - name: copy all files in artifact folder
        run: mkdir artifact && cp target/*.jar artifact  
      - name: upload arifacts
        uses: actions/upload-artifacts@v2
        with:
          name: artifacts
          path: artifact
