name: mainci

on:
  pull_request:
    branches:    
      - master
      - develop
      - feature
     
  workflow_dispatch:
  
jobs:
  pipelineconfig:
     uses: sark1-projects/Maven-Project1/.github/workflows/pipelineconfig.yml@master
     
 
  compile-java-maven:
     needs: pipelineconfig
     runs-on: ubuntu
     #if: "contains(needs.pipelineconfig.outputs.buildTool, 'maven') && contains(needs.pipelineconfig.outputs.language, 'java')"
     steps:
      - name: create artifact
        run: echo "subhajit" > subhajit.txt
      - uses: actions/cache@v2
        id: rt1
        with:
          path: ./*
          key: ${{ github.sha }}

 
