name: main2
on:
  pull_request:
    branches:    
      - master
      - develop
      - feature
     
  workflow_dispatch:
  
jobs:
  pipelineconfig:
     uses: sark1-projects/Maven-Project1/.github/workflows/pipelineconfig.yml@master
     
 
  compile-java-maven:
     needs: pipelineconfig
     if: "contains(needs.pipelineconfig.outputs.buildTool, 'maven') && contains(needs.pipelineconfig.outputs.language, 'java')"
     uses: sark1-projects/Main/.github/workflows/java-node-maven-npm.yml@main
     with:
      java-version: ${{ needs.pipelineconfig.outputs.javaVersion}}
   
  compile-java-node-maven-npm:
     needs: pipelineconfig
     if: "contains(needs.pipelineconfig.outputs.buildTool, 'maven-npm') && contains(needs.pipelineconfig.outputs.language, 'java-node')"
     uses: sark1-projects/Main/.github/workflows/java-node-maven-npm.yml@main
     with:
      java-version: ${{ needs.pipelineconfig.outputs.javaVersion}}
      node-version: ${{ needs.pipelineconfig.outputs.nodeVersion}}
     
    
    
  Code-Quality:
    needs: [compile-java-node-maven-npm,compile-java-maven]
    if: |
       !failure() && !cancelled() && 
       (success('compile-java-node-maven-npm') || success('compile-java-maven'))
    runs-on: ubuntu-latest
    container: 
      image: ubuntu
    steps:
       - uses: actions/checkout@v3
       - name: code Analysis
         run: echo 'mvn sonar:sonar'
       - name: Download artifacts
         uses: actions/download-artifact@v2
         with:
           name: artifacts
       - name: show artifacts
         
         run: echo artifact downloaded

  security-scan:

    needs: [Code-Quality]
    if: |
       !failure() && !cancelled() && 
       success('Code-Quality')
    #if: github.event.ref == 'refs/heads/develop'
    runs-on: ubuntu-latest
    steps:
       - uses: actions/checkout@v3
       - name: scanning
         run: echo 'scanning'
         
  Quality-Gates:
    needs: security-scan
    if: |
       !failure() && !cancelled() && 
       success('security-scan')
    #if: github.event.ref == 'refs/heads/develop'
    runs-on: ubuntu-latest
    steps:
       - uses: actions/checkout@v3
       - name: CodeAnalysis_Quality_gates
         run: echo 'code analysis quality gates'
       - name: SecurityAnalysis_Quality_gates
         run: echo 'security analysis quality gates'
         
  ChangeRequest_Validation:
   
    needs: Quality-Gates
    if: |
       !failure() && !cancelled() && 
       success('Quality-Gates') && github.event.ref == 'refs/heads/master'
    
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      - name: validations status
        run: echo 'ChangeRequest Validation "performed"'
    
  Deploy_feature:
   
    runs-on: ubuntu-latest
    environment: 
      name: Development 
    needs: Quality-Gates
    if: |
       !failure() && !cancelled() && 
       success('Quality-Gates') && github.event.ref == 'refs/heads/feature'
    steps:
       - uses: actions/checkout@v3
       - name: deploying
         run: echo 'feature branch'
   
  
  Deploy_Develop:
    
    runs-on: ubuntu-latest
    environment: 
      name: Staging 
    needs: Quality-Gates
    if: |
       !failure() && !cancelled() && 
       success('Quality-Gates') && github.event.ref == 'refs/heads/develop'
    steps:
       - uses: actions/checkout@v3
       - name: deploying into develop branch
         run: echo 'develop branch'
         
  Deploy_Master:
    
    runs-on: ubuntu-latest
    environment: 
      name: Production
    needs: [ChangeRequest_Validation]
    if: |
       !failure() && !cancelled() && 
       success('ChangeRequest_Validation') && github.event.ref == 'refs/heads/master'
    steps:
       - uses: actions/checkout@v3
       - name: deploying to Prod
         run: echo 'master branch'
