name: mainci

on:
  pull_request:
    branches:    
      - master
      - develop
      - feature
     
  workflow_dispatch:
  
jobs:
  pipelineconfig:
     uses: sark1-projects/Maven-Project1/.github/workflows/pipelineconfig.yml@master
     
 
  compile-java-maven:
     needs: pipelineconfig
     runs-on: ubuntu
     if: "contains(needs.pipelineconfig.outputs.buildTool, 'maven') && contains(needs.pipelineconfig.outputs.language, 'java')"
     steps:
      - uses: sark1-projects/Main/.github/workflows/java-maven.yml@main
        with:
         java-version: ${{ needs.pipelineconfig.outputs.javaVersion}}
      - uses: actions/cache@v2
        id: restore-build
        with:
          path: ./*
          key: ${{ github.sha }}

 
