name: npm

on:
 workflow_call:
    inputs:
       image_name:
           type: string
           required: true
    secrets:
        registry_username:
             required: true
        registry_password:
             required: true

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
      - name: pull the Docker image
        run: docker pull ${{ inputs.image_name }}
      - name: docker run
        run: |
           docker container run ${{ inputs.image_name }}
      - name: Install dependencies
        run: echo "npm run build"
      - name: Run test
        run: echo "npm run test"
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - name: login
        run: echo "login success"
      - name: tag
        run:  docker tag ${{ inputs.image_name }} subhajit1/${{ inputs.image_name }}:latest
      - name: push
        run: docker push subhajit1/${{ inputs.image_name }}:latest
      - name: uploading to jFrog
        run: echo 'jfrog'
