name: one
on:
  workflow_dispatch:
jobs:

  
  job1:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "${{ github.run_id }}"
         
          echo 'github.event.ref'
          echo "github.event.ref"
          echo ${{github.event.ref}}
