name: one
on:
  pull_request:
    branches:    
      - master
      - develop
      - feature
     
  workflow_dispatch:
  
jobs:
  pipelineconfig:
     uses: sark1-projects/Maven-Project1/.github/workflows/pipe.yml@master
     
 
  compile-java-maven:
     needs: pipelineconfig
     if: "contains(needs.pipelineconfig.outputs.buildTool, 'maven') && contains(needs.pipelineconfig.outputs.language, 'java')"
     runs-on: ubuntu-latest
     steps:
      - run: |
            echo ${{ github.event.repository.name }}
            echo ${{ github.event.ref }}
          
