name: oone
on: 
  workflow_dispatch:
jobs:
  
  oone:
    runs-on: ubuntu-latest
    
    steps: 
      - run: |
        echo github.event.ref
        echo 'github.event.ref'
        echo "github.event.ref"
        echo ${{github.event.ref}}
